In [5]:
# Stage 05 â€” Data Storage 

from pathlib import Path
import pandas as pd

project_root = Path.cwd().parent
RAW_DIR = project_root / "data" / "raw"
PROCESSED_DIR = project_root / "data" / "processed"

# Load raw (KO daily prices)
prices = pd.read_csv(RAW_DIR / "ko_prices.csv", parse_dates=["Date"])

# Every Close cell to numeric
prices["Close"] = pd.to_numeric(prices["Close"], errors="coerce")

# Daily return
df_proc = (
    prices[["Date", "Close"]]
    .rename(columns={"Close": "close"})
    .sort_values("Date")
    .assign(daily_ret=lambda d: d["close"].pct_change())
)

# Save
out_path = PROCESSED_DIR / "ko_daily_returns.parquet"
df_proc.to_parquet(out_path, index=False)

print("Saved:", out_path)
print(df_proc.info())
display(df_proc.head())
display(df_proc.tail())

Saved: c:\Users\marti\bootcamp_martin_barreto\project\data\processed\ko_daily_returns.parquet
<class 'pandas.core.frame.DataFrame'>
Index: 6449 entries, 1 to 0
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6448 non-null   datetime64[ns]
 1   close      6448 non-null   float64
 2   daily_ret  6448 non-null   float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 201.5 KB
None

C:\Users\marti\AppData\Local\Temp\ipykernel_18720\1795080163.py:21: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .assign(daily_ret=lambda d: d["close"].pct_change())

        Date      close  daily_ret
1 2000-01-03  13.815726        NaN
2 2000-01-04  13.831048   0.001109
3 2000-01-05  13.953581   0.008859
4 2000-01-06  13.968897   0.001098
5 2000-01-07  14.887897   0.065789

           Date      close  daily_ret
6445 2025-08-18  69.129997  -0.011299
6446 2025-08-19  70.129997   0.014466
6447 2025-08-20  70.699997   0.008128
6448 2025-08-21  70.660004  -0.000566
0           NaT        NaN   0.000000